- fields/types/gcsimage/GcsImageType.js
- package.json
@hcchien 
extract image exif, such as Artist, ImageDescription, ImageWidth, ImageHeight
> extract image info

- fields/types/gcsimage/GcsImageType.js
- lib/gcsHelper.js
- package.json
@hcchien 
related to https://github.com/twreporter/plate/pull/6
> add resize image functionality

- fields/types/html/CONSTANT.js
- fields/types/html/DraftHtmlConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/LinkButton.js
- fields/types/html/entityDecorator.js
1. use decorator for link entity
2. add link input field to let editors edit link url
3. litte code refactor for HtmlField.
@hcchien 
@garfieldduck
> enable link entity

- admin/client/components/ImageGrid.js
- admin/client/components/ImagesEditor.js
- admin/client/components/ImagesSelection.js
- fields/types/html/image/ImageButton.js
- package.json
> add shouldComponentUpdate for pure render

- admin/client/components/ImageSelector.js
- admin/client/components/ImagesDiff.js
- admin/client/components/ImagesSelection.js
- admin/public/styles/keystone.less
- admin/public/styles/react/react-slider.less
- fields/types/html/CONSTANT.js
- fields/types/html/DraftConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/base/MediaBlock.js
- fields/types/html/image-diff/ImageDiffBlock.js
- fields/types/html/image/ImageBlock.js
- fields/types/html/image/ImageButton.js
- fields/types/html/modifiers/image-diff/image-diff-modifier.js
- fields/types/html/modifiers/image-diff/insertImageDiffBlock.js
- fields/types/html/modifiers/index.js
- fields/types/html/slideshow/SlideshowBlock.js
- package.json
- add imageDiff button on editor tool
- show imageDiff component after selecting two images.
- add imageDiff component and corresponding css.
@hcchien
> imageDiff component

- fields/types/gcsimage/GcsImageType.js
- fields/types/html/CONSTANT.js
- fields/types/html/image/ImageBlock.js
- fields/types/html/modifiers/image-diff/insertImageDiffBlock.js
- fields/types/html/modifiers/image/insertImageBlock.js
- fields/types/html/modifiers/image/replaceImageBlock.js
- fields/types/html/modifiers/slideshow/insertSlideshowBlock.js
- fields/types/html/modifiers/slideshow/replaceSlideshowBlock.js
- fields/types/html/slideshow/SlideshowBlock.js
- package.json
1. get image width and height while uploading and store those info in the db.
2. set needed props of image into the draft entity object.
@garfieldduck
> Code change

- fields/types/html/DraftConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/base/block-style-fn.js
- fields/types/html/entityDecorator.js
- fields/types/html/quote/quote-decorator.js
- fields/types/html/quote/quote-types.js
- use quote-decorator to render pumping/forward/intro quote in Draftjs Editor
- use quote-block-style to add specific css style
- output blockquote tag in html object with different classname
- output blockquote type in apiData object with different styles
@hcchien
> enable pumping quote, forward quote and introduction quote

- admin/client/components/ImagesDiff.js
- fields/types/html/AtomicBlockProcessor.js
- fields/types/html/CONSTANT.js
- fields/types/html/DraftConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/base/atomic-block.js
- fields/types/html/base/style-button.js
- fields/types/html/embedded-code/embedded-code-block.js
- fields/types/html/embedded-code/embedded-code-bt.js
- fields/types/html/embedded-code/embedded-code-editing-block.js
- fields/types/html/link/link-decorator.js
- fields/types/html/link/link-editing-block.js
- fields/types/html/modifiers/index.js
- fields/types/html/modifiers/insert-atomic-block.js
- fields/types/html/modifiers/replace-block.js
- fields/types/html/quote/quote-decorator.js
- fields/types/html/slideshow/slideshow-block.js
- add embedded-code-block, embedded-code-bt and embedded-code-editing-block
- DraftConverter
- output embedded code in html object
- output embedded code in apiData object
- code change for CONSTANT.js
@hcchien
> Embedded code block for Draftjs editor

- admin/client/columns.js
- admin/client/fields.js
- admin/client/filters.js
- fields/types/gcsfile/GcsFileColumn.js
- fields/types/gcsfile/GcsFileField.js
- fields/types/gcsfile/GcsFileFilter.js
- fields/types/gcsfile/GcsFileType.js
- lib/fieldTypes.js
- lib/list/getSearchFilters.js
- lib/updateHandler.js
- upload file to google cloud storage
@hcchien
> Add GcsFile field

- admin/public/styles/draftjs/editor.less
- admin/public/styles/keystone/item.less
- fields/types/html/HtmlField.js
- added an enlarge button to the HTML editor
- HTML editor will fill out the screen after the enlarge button is clicked
> added enlarge HtmlEditor to fullscreen function

- fields/types/html/HtmlField.js
- fields/types/html/base/style-button.js
- fields/types/html/embedded-code/embedded-code-bt.js
- fields/types/html/embedded-code/embedded-code-editing-block.js
- fields/types/html/image/image-button.js
- fields/types/html/link/link-button.js
- fields/types/html/link/link-editing-block.js
> fix EmbeddedCodeBt missing, and let style bt clickable

- fields/types/html/base/block-alignment-wrapper.js
- fields/types/html/base/bt-wrapper.js
- fields/types/html/base/button-icon.js
- fields/types/html/embedded-code/embedded-code-bt.js
- fields/types/html/embedded-code/embedded-code-editing-block.js
- fields/types/html/image/image-button.js
- fields/types/html/image/image-editing-block.js
- fields/types/html/link/link-button.js
- fields/types/html/link/link-editing-block.js
- add bt-wrapper.js, which is used to make button clickable and click to
show editing block
> Code refactor

- fields/types/html/CONSTANT.js
- fields/types/html/DraftConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/annotation/annotation-bt.js
- fields/types/html/annotation/annotation-decorator.js
- fields/types/html/annotation/annotation-editing-block.js
- fields/types/html/entityDecorator.js
- use CompositeDecorator to render annotation
- add annotation-bt and annotation-editing-block
- make DraftConverter convert annotation entity
@hcchien @garfieldduck 
Please help to review if you have free time, thanks
> add annotation feature

- fields/types/html/CONSTANT.js
- fields/types/html/DraftConverter.js
- fields/types/html/HtmlField.js
- fields/types/html/base/atomic-block.js
- fields/types/html/base/entity-editing-block.js
- fields/types/html/info-box/info-box-block.js
- fields/types/html/info-box/info-box-bt.js
- fields/types/html/info-box/info-box-editing-block.js
- fields/types/html/modifiers/insert-atomic-block.js
> add info box custom block

- fields/types/html/AtomicBlockProcessor.js
- fields/types/html/HtmlField.js
- fields/types/html/embedded-code/embedded-code-editing-block.js
- fields/types/html/modifiers/insert-atomic-block.js
> add caption in embedded code editing block

- fields/types/html/AtomicBlockProcessor.js
> insert infobox atomic block

- admin/client/components/ImageSelector.js
> use mobile version image for selection

- fields/types/gcsimage/GcsImageType.js
> calculate the width and height of resized images by original aspect ratio

- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesField.js
- fields/types/gcsimages/GcsImagesType.js
1. make extractIptc configurable
2. uploading multiple photos to gcs at the same time
@hcchien
> Update GcsImageType.js, GcsImagesField.js and GcsImagesType.js

- admin/client/components/ImageSelector.js
- fields/types/imagerelationship/ImageRelationshipField.js
- lib/parseImageAPIResponse.js
- search by description in ImageSelector.js
- add lib/parseImageAPIResponse.js
@hcchien
> Update Image handling

- fields/types/gcsimages/GcsImagesType.js
Uploading too many images at a time will cause ```socket hang up``` problem, and this problem will make the program fails.
use ```async.eachLimit``` to restrict the number of requests to gcs.
This make the program only build one connection to gcs at a time.
@hcchien
> handle gcs socket hang up issue

- package.json
fields/types/html/modifiers/insert-atomic-block.js
> uploading audio file and fix bug that we can not upload too many images to gcs at a time

- fields/types/imagerelationship/ImageRelationshipField.js
> Fix bug, removing heroImage in the post fails

- admin/client/components/AudioGrid.js
- admin/client/components/AudioSelector.js
- lib/parseAPIResponse.js
[reference](https://github.com/twreporter/plate/pull/31)
@hcchien
> Use html property of description draftjs obj

- fields/types/html/editor/base/entity-editing-block.js
- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/draft-editor.js
- fields/types/html/editor/info-box/info-box-editing-block.js
- fields/types/html/editor/mixins/draftjs-editing-mixin.js
[request](https://trello.com/c/PrJckhnI/33-infobox-hyperlink
) by editor 
I use draft editor to let editor to edit the ```body``` of info box,
and ```body``` will be exposed as html.
Hence ```InfoBox``` component of twreporter-react will need to change as well,
I will make a pull request later.
@hcchien @garfieldduck
> Use Draft editor to edit body of InfoBox

- admin/client/components/AudioGrid.js
- admin/public/styles/keystone.less
- fields/types/html/HtmlField.js
- fields/types/html/editor/audio/audio-block.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/image-diff/image-diff-block.js
- fields/types/html/editor/info-box/info-box-block.js
- fields/types/html/editor/mixins/atomic-block-renderer-mixin.js
- package.json
> Use react-article-components to render atmoic block

- admin/client/components/ImageGrid.js
- admin/client/components/ImageSelector.js
- admin/client/components/mixins/SelectorMixin.js
1. Bug fix: search images by keyword
2. Style change: add select icon and remove icon
@hcchien
> Bug fix and image selector style change

- admin/client/components/ImageGrid.js
- admin/public/styles/draftjs/slideshow-style.less
- admin/public/styles/keystone.less
- fields/types/html/editor/slideshow/slideshow-block.js
- package.json
同時讓 editor 能夠重複編輯 slideshow
@hcchien
> Use slideshow component react-article-components

- fields/types/html/HtmlField.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/editor-buttons.js
- fields/types/html/editor/entities.js
- fields/types/html/editor/modifiers/index.js
- fields/types/html/editor/modifiers/insert-atomic-block.js
- fields/types/html/editor/quote/block-quote-block.js
- fields/types/html/editor/quote/block-quote-bt.js
- fields/types/html/editor/quote/block-quote-editing-block.js
> Add BlockQuote Component and some code refactor

- admin/public/styles/draftjs/editor.less
- admin/public/styles/draftjs/rich-editor.less
- fields/types/html/HtmlField.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/base/block-wrapper.js
- fields/types/html/editor/constants/layout-style.js
- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/editor-buttons.js
- fields/types/html/editor/entities.js
- fields/types/html/editor/image/image-block.js
- fields/types/html/editor/inline-styles-processor.js
- fields/types/html/editor/youtube/youtube-block.js
- fields/types/html/editor/youtube/youtube-bt.js
- fields/types/html/editor/youtube/youtube-editing-block.js
add ```clearfix``` to fix float side-effect when aligning.
@hcchien
> Editor style tuning and add Youtube block

- fields/types/html/editor/image-diff/image-diff-block.js
- fields/types/html/editor/modifiers/replace-block.js
1. Bug fix. Fix the problem we can't change the images of existing Slideshow component.
2. Make ImageDiff component editable.
@hcchien
> Two updates

- fields/types/html/editor/annotation/annotation-block.js
- fields/types/html/editor/base/editing-bt.js
- fields/types/html/editor/embedded-code/embedded-code-block.js
- fields/types/html/editor/image-diff/image-diff-block.js
- fields/types/html/editor/info-box/info-box-block.js
- fields/types/html/editor/mixins/atomic-block-renderer-mixin.js
- fields/types/html/editor/quote/block-quote-block.js
- fields/types/html/editor/slideshow/slideshow-block.js
- fields/types/html/editor/youtube/youtube-block.js
- fields/types/imagerelationship/ImageRelationshipField.js
> Bug fix. Fix missing HeroImage thumbnail

- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesType.js
> DELETE LOCAL UPLOADED FILES

- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesColumn.js
- fields/types/gcsimages/GcsImagesType.js
> delete local files synchronously and render image-collection lists efficiently

- fields/types/gcsimage/GcsImageType.js
Deleting local file too early.
> Fix bug. Update fields/types/gcsimage/GcsImageType.js

- fields/types/html/HtmlField.js
- fields/types/html/editor/annotation/annotation-decorator.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/editor-buttons.js
- fields/types/html/editor/entities.js
- fields/types/html/editor/inline-styles-processor.js
- fields/types/html/editor/link/link-decorator.js
- fields/types/html/editor/mixins/entity-editing-block-mixin.js
- fields/types/html/editor/modifiers/index.js
- fields/types/html/editor/slideshow/slideshow-block.js
- handle entity type is lower case
- uppercase all the entity type
@hcchien
> Backward Compatible

- fields/types/html/HtmlField.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/editor-buttons.js
- fields/types/html/editor/entities.js
- fields/types/html/editor/image-link/image-link-block.js
- fields/types/html/editor/image-link/image-link-bt.js
- fields/types/html/editor/image-link/image-link-editing-block.js
- fields/types/html/editor/modifiers/index.js
@hcchien @garfieldduck 
Request from 小偉, he wants to only give image url; not to upload image file.
> Add ImageLink atomic block

- admin/public/styles/keystone.less
- admin/public/styles/keystone/base.less
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/audio/audio-block.js
- fields/types/html/editor/embedded-code/embedded-code-block.js
- fields/types/html/editor/image-diff/image-diff-block.js
- fields/types/html/editor/image-link/image-link-block.js
- fields/types/html/editor/image/image-block.js
- fields/types/html/editor/info-box/info-box-block.js
- fields/types/html/editor/quote/block-quote-block.js
- fields/types/html/editor/slideshow/slideshow-block.js
- fields/types/html/editor/youtube/youtube-block.js
- gulpfile.js
- package.json
> Handle Embedded Block

- admin/public/styles/draftjs/rich-editor.less
- fields/types/html/HtmlField.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/base/atomic-block-switcher.js
- fields/types/html/editor/constants/layout-style.js
- fields/types/html/editor/draft-converter.js
> Add default blockquote block of draftjs back

- fields/types/html/editor/api-data-instance.js
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/draft-converter.js
> Add target="_blank" attribute of LINK. Fix ImageLink component bug.

- fields/types/html/editor/draft-converter.js
- fields/types/html/editor/inline-styles-processor.js
> Fix bug. Annotation works abnormally

- CHANGELOG.md
- fields/types/html/editor/atomic-block-processor.js
- fields/types/html/editor/embedded-code/embedded-code-block.js
- package.json
> Get height and width of iframe if provided for Embedded component

- fields/types/date/DateField.js
> Show the GMT+8 date time

- CHANGELOG.md
- fields/types/html/HtmlField.js
- fields/types/html/editor/mixins/entity-editing-block-mixin.js
- package.json
> Insert soft new line

- fields/types/html/editor/entities.js
> Increase slideshow slides

- fields/types/html/HtmlField.js
> Workaround for using twreporter-react pkg without error

- CHANGELOG.md
- fields/types/html/editor/draft-converter.js
- package.json
> Bug fix. Store ordered-list and unordered-list in the right way

- fields/types/gcsfile/GcsFileType.js
- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesType.js
- lib/gcsHelper.js
Add Cache-Control for caching multimedia elements for a week.
@garfieldduck
> Add Cache-Control for uploading images and audios onto GCS

- CHANGELOG.md
- admin/client/columns.js
- admin/client/fields.js
- admin/client/filters.js
- fields/types/preview/PreviewColumn.js
- fields/types/preview/PreviewField.js
- fields/types/preview/PreviewFilter.js
- fields/types/preview/PreviewType.js
- lib/fieldTypes.js
- lib/list/getSearchFilters.js
- package.json
Since we have preview page to render draft state article,
we have to add preview button and preview column for linking to preview page.
> Preview button and preview column for linking to preview page

- CHANGELOG.md
- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesType.js
- package.json
> Pass filetype into resize function while resizing gcsimage(s)

- CHANGELOG.md
- fields/types/titleposition/TitlePositionField.js
> Add two more relationship between title and leading image

- CHANGELOG.md
- admin/server/templates/item.jade
- lib/session.js
- package.json
Show all the user avators when they are editing the same page
>  Bump version to 0.6.3

- CHANGELOG.md
- fields/types/gcsimage/GcsImageType.js
- fields/types/gcsimages/GcsImagesType.js
- package.json
replace `image-size` by `probe-image-size` because of [this issue](https://github.com/image-size/image-size/issues/96)
> Replace `image-size` by `probe-image-size`

- CHANGELOG.md
- admin/server/app/createDynamicRouter.js
- admin/server/templates/item.jade
- admin/server/templates/list.jade
- fields/types/preview/PreviewColumn.js
- fields/types/preview/PreviewField.js
- lib/core/render.js
- package.json
https://github.com/twreporter/plate/pull/162
> refactor: load preview origin from config

- admin/public/styles/keystone/list.less
- fields/types/gcsimage/GcsImageColumn.js
- fields/types/gcsimage/GcsImageField.js
- fields/types/gcsimage/GcsImageFilter.js
- fields/types/gcsimage/GcsImageType.js
1. finalize supported image file type: add `image/bmp` type
2. fix alert message not showing
3. ask end users to check slack channel after uploading image. (also see PR [refactor: update models/Image.js. add slack channel notice](https://github.com/twreporter/plate/pull/174))
4. enable search by iptc metadata
> refactor: update gcsimage 

- fields/types/gcsimage/GcsImageField.js
- removes '上午', '下午' condition
- add timezone if existed
> refactor: update GcsImageField.js

- CHANGELOG.md
- package.json
This patch updates the CHANGELOG and version tag in package.json.
> chore: bump version to v0.9.4-rc.0

- CHANGELOG.md
This patch bumps the version to the stable version v0.9.4
> chore: bump version to v0.9.4

- fields/types/date/DateFilter.js
Resolves [TWREPORTER-126](https://twreporter-org.atlassian.net/browse/TWREPORTER-126).
This patch fixes date filter to choose dates in 'between' mode properly.
> fix: date filter on choosing 'between'

- admin/client/fields.js
- admin/server/routes/item.js
- fields/types/Field.js
- fields/types/gcsavatar/GcsAvatarField.js
- fields/types/gcsavatar/GcsAvatarType.js
- lib/fieldTypes.js
- lib/session.js
- lib/updateHandler.js
Address [TWREPORTER-119](https://twreporter-org.atlassian.net/browse/TWREPORTER-119).
> feat: add uploading avatar support

- fields/types/gcsavatar/GcsAvatarType.js
This change updates cache-control for avatar before uploading.
> refactor: update cache-control for avatar

- admin/server/templates/includes/script/keystone.jade
This patch enables the signout url.
> feat: enable signout url

- fields/types/gcsfile/GcsFileField.js
- fields/types/gcsimage/GcsImageField.js
- fields/utils/replace-gcs-url-origin.js
Address [TWREPORTER-320](https://twreporter-org.atlassian.net/browse/TWREPORTER-320).
> refactor: change public url prefix to utilize CDN cache

- admin/public/styles/keystone/item.less
- admin/public/styles/keystone/toolbar.less
- This patch fix defect [`[defect] keystone 單一 tag 頁：search 露出來`](https://app.asana.com/0/0/1203964343575786/f)
> fix: search bar style

- CHANGELOG.md
- package.json
> chore: bump version v0.9.10

- fields/types/CategoryConstants.js
[[資訊架構] 新增「基金會消息」主分類-keystone](https://app.asana.com/0/1203699264568808/1205988685100796/f)
N/A
> feat: add foundation category set ids in white list

- admin/client/components/CreateReviewModal.js
- admin/client/views/home.js
- admin/client/views/latestList.js
- admin/client/views/list.js
- admin/client/views/reviewDndContainer.js
- admin/client/views/reviewList.js
- package.json
- yarn.lock
[[會員制]重要報導回顧-CMS](https://app.asana.com/0/1203699264568808/1206721264374714/f)
ref: https://github.com/twreporter/keystone/pull/231
N/A
> feat: add modals & components for review page

- admin/client/views/reviewDndContainer.js
- lib/updateHandler.js
fix defects in [[會員制]重要報導回顧-CMS](https://app.asana.com/0/1203699264568808/1206721264374714/f)
N/A
> fix: add `maxLength` & `maxLengthErr` options for text

- fields/types/html/HtmlField.js
- fields/types/html/HtmlType.js
- fields/types/html/editor/entities.js
- fields/types/relationship/RelationshipField.js
- fields/types/relationship/RelationshipType.js
- fields/types/relationship/SortableList.js
[[會員制]重要報導追蹤-CMS](https://app.asana.com/0/1203699264568808/1207085276870878/f)
N/A
> feat: add `selectWithSort` option for `Relationship` type

- fields/types/html/HtmlField.js
- fields/types/html/HtmlType.js
- fields/types/html/editor/entities.js
[[維運] 文章頁新增版型：滿版版型-CMS](https://app.asana.com/0/1203699264568808/1207629974038928/f)
N/A
> feat: add `embededOnly` options for HTML type

- CHANGELOG.md
- fields/types/html/HtmlField.js
- fields/types/html/HtmlType.js
- fields/types/html/editor/entities.js
- package.json
> fix: embeded typo
